### ISSUE TITLE
Doesn't work under FreeBSD + apache 2.4

### ISSUE THREAD

**Issue by ErickJStark** [skyride/evething-2#9]
My steps (under **root** user):
1. mkdir -p /usr/local/wsgi/venv
2. Steps 1-9 from **Common install steps** (on step 7 i got: `manage.py: error: no such option: --all`)
3. Create site evething.\<mydomain\> on my DNS
4. Add **evething.\<mydomain\>.conf** in **apache24/Virtual** folder with this content:
<pre>
    &lt;VirtualHost *:80&gt;
        ErrorLog "/var/log/www/evething.&lt;mydomain&gt;-error.log"
        TransferLog "/var/log/www/evething.&lt;mydomain&gt;-access.log"
        CustomLog "/var/log/www/evething.&lt;mydomain&gt;-custom.log" combined
        DocumentRoot "/usr/local/www/evething.&lt;mydomain&gt;"
        ServerName evething.&lt;mydomain&gt;
        ServerAlias www.evething.&lt;mydomain&gt;
        &lt;Directory "/usr/local/www/evething.&lt;mydomain&gt;"&gt;
            Require all granted
        &lt;/Directory&gt;
        Alias /static/      /usr/local/www/evething.&lt;mydomain&gt;/static/
    &lt/VirtualHost&gt
</pre>

5. Create **evething.conf** in **apache24/Includes** folder with this content:
<pre>
    WSGIDaemonProcess evething threads=2 user=nobody python-path=/usr/local/wsgi/venv/thingenv/evething-2:/usr/local/wsgi/venv/thingenv/lib/python2.7/site-packages
    WSGIProcessGroup evething
    WSGIScriptAlias / /usr/local/wsgi/venv/thingenv/evething-2/evething/wsgi.py
    WSGIPythonHome /usr/local/wsgi/venv/thingenv
    &lt;Directory /usr/local/wsgi/venv/thingenv/evething-2&gt;
        &lt;Files wsgi.py&gt;
            Require all granted
        &lt;/Files&gt;
    &lt;/Directory&gt;
</pre>

6. Restart apache
7. Run **python manage.py collectstatic**

Try to visit **http://evething.<mydomain&gt;** and got 
**500 Internal Server Error**

File **evething.\<mydomain>-error.log** contains:
<pre>
XXX mod_wsgi (pid=28734): Failed to exec Python script file '/usr/local/wsgi/venv/thingenv/evething-2/evething/wsgi.py'.
XXX mod_wsgi (pid=28734): Exception occurred processing WSGI script '/usr/local/wsgi/venv/thingenv/evething-2/evething/wsgi.py'.
XXX Traceback (most recent call last):
XXX   File "/usr/local/wsgi/venv/thingenv/evething-2/evething/wsgi.py", line 33, in <module>
XXX     application = get_wsgi_application()
XXX   File "/usr/local/wsgi/venv/thingenv/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
XXX     django.setup()
XXX   File "/usr/local/wsgi/venv/thingenv/lib/python2.7/site-packages/django/__init__.py", line 20, in setup
XXX     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
XXX   File "/usr/local/wsgi/venv/thingenv/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
XXX     self._setup(name)
XXX   File "/usr/local/wsgi/venv/thingenv/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
XXX     self._wrapped = Settings(settings_module)
XXX   File "/usr/local/wsgi/venv/thingenv/lib/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
XXX     % (self.SETTINGS_MODULE, e)
XXX ImportError: Could not import settings 'evething.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named evething.settings
</pre>

**Comment by skyride** [comment]
Hey dude, couple things.

Firstly, that error at your step 2, looks like I missed the part when I updated the instructions yonks ago. Just ignore steps 6-8 in those instructions and run `./manage.py migrate` instead.

Secondly, the main error you're getting is actually an issue with your apache config. The one in the common install steps hasn't been updated since I forked the original evething and I haven't personally run it on apache in about 2 years (instead using Nginx + UWSGI) so I can't tell you for sure what's wrong there.

If it makes life any easier, I'm working on a docker-compose installer that should make it just a case of running a single script. Should hopefully have it done this weekend.

**Comment by ErickJStark** [comment]
Good time of day, Adam!
Thanx for your answer.
Can you help me to implement this application anyway. I ready to make any
other way, but i don`t know how, because instruction doesn`t contain any
steps/sections about docker and/or nginx+uwsgi.
P.S. My python`s expirience is lesser than zero, but I really can`t find
evething.settings file in any (sub)folders of deployed environment...

2018-05-13 1:00 GMT+03:00 Adam Findlay <notifications@github.com>:

**Comment by solamance** [comment]
Hi Erick,

I've run into similar errors when the permissions on my web root for the project aren't set correctly - it is possible that your Apache user doesn't own the folder. 

The scripts are failing to execute, and the .settings module isn't found. Double check it's in the correct directory and make sure you're showing all when you search - .settings files like to hide sometimes.

Hope that helps!

**Comment by ghost** [comment]
Hi Erick,

I ran into a similar issue when installing this - I ended up doing a whole bunch of fixing before I Realized that my dependencies hadn't installed correctly. 

Install mysql dev tools (apt-get install libmysqlclient-dev) - step 4 will fail without it. Then re-run step four (pip install -r requirements.txt). 

Hope that helps!
